//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbuPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akademisyen
    {
        public int AkademisyenId { get; set; }
        public string AkademisyenAdi { get; set; }
        public string AkademisyenSoyadi { get; set; }
        public string AkademisyenSifre { get; set; }
        public string AkademisyenMail { get; set; }
        public Nullable<int> AkademisyenRolID { get; set; }
        public Nullable<System.DateTime> AkademisyenUyelikTarihi { get; set; }
        public Nullable<int> AkademisyenBolumID { get; set; }
        public Nullable<int> ProfilResimId { get; set; }
        public Nullable<bool> KabulDurumu { get; set; }
        public Nullable<bool> Aktiflik { get; set; }
    }
}
