//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbuPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DosyaGonderimleri
    {
        public int DosyaGonderimID { get; set; }
        public int DosyayıGonderenID { get; set; }
        public int DosyayiAlanID { get; set; }
        public int GonderilenDosyaID { get; set; }
    }
}
