//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbuPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsIlani
    {
        public int Id { get; set; }
        public string SirketAdi { get; set; }
        public string SirketSehir { get; set; }
        public string SirketPozisyonu { get; set; }
        public Nullable<int> DuyuruId { get; set; }
    }
}
