//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbuPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiselDetay
    {
        public int Id { get; set; }
        public string CalistigiFirma { get; set; }
        public string CalistigiFirmaninIli { get; set; }
        public string MezuniyetYili { get; set; }
        public string Bolumu { get; set; }
        public Nullable<int> KullaniciId { get; set; }
    }
}
