//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbuPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public int OgrenciNo { get; set; }
        public string OgrenciAdi { get; set; }
        public string OgrenciSoyadi { get; set; }
        public string OgrenciSifre { get; set; }
        public string OgrenciTelefon { get; set; }
        public string OgrenciMail { get; set; }
        public int OgrenciRolID { get; set; }
        public System.DateTime OgrenciUyelikTarihi { get; set; }
        public int OgrenciBolumID { get; set; }
        public Nullable<int> ProfilResimId { get; set; }
        public string OgrenciSinif { get; set; }
        public Nullable<bool> Aktiflik { get; set; }
    }
}
