//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbuPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SosyalMedya
    {
        public int Id { get; set; }
        public string SosyalMedyaLinkedin { get; set; }
        public string SosyalMedyaFacebook { get; set; }
        public string SosyalMedyaInstagram { get; set; }
        public string DigerSite { get; set; }
        public int KullaniciId { get; set; }
    }
}
