//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CbuPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int Id { get; set; }
        public Nullable<int> GonderiId { get; set; }
        public string Yorum1 { get; set; }
        public Nullable<int> YorumYapanId { get; set; }
        public Nullable<System.DateTime> YorumTarih { get; set; }
        public Nullable<bool> YorumDurumu { get; set; }
    }
}
